parameters:
    csbill_payment.menu.top.class: CSBill\PaymentBundle\Menu\PaymentsMenu
    payum.class: CSBill\PaymentBundle\Payum

services:
    payum.static_registry:
        class: CSBill\PaymentBundle\Payum
        arguments: [[], [], []]
        calls:
            - [setContainer, [@service_container]]

    csbill_payment.menu.top:
        class: %csbill_payment.menu.top.class%
        tags:
            - { name: cs_core.menu, menu: top_right, method: topRightMenu }
            - { name: cs_core.menu, menu: top, method: topMenu }

    #csbill.payment.payum.paypal_express.action.capture_payment_action:
        #class: CSBill\PaymentBundle\Action\PaypalExpress\CapturePaymentAction
        #arguments: [@payum.security.token_factory, @csbill.money.formatter]
        #tags:
            #- { name: payum.action, factory: paypal_express_checkout_nvp }

    #csbill.payment.payum.paypal_express.action.notify_payment_action:
        #class: CSBill\PaymentBundle\Action\PaypalExpress\NotifyPaymentAction
        #arguments: [@doctrine.orm.entity_manager]
        #tags:
            #- { name: payum.action, factory: paypal_express_checkout_nvp }

    csbill.payment.payum.paypal_express.action.payment_status_action:
        class: CSBill\PaymentBundle\Action\PaypalExpress\PaymentDetailsStatusAction
        tags:
            - { name: payum.action, factory: paypal_express_checkout_nvp, prepend: true }

    csbill.payment.payum.offline.action.status_action:
        class: CSBill\PaymentBundle\Action\Offline\StatusAction
        tags:
            - { name: payum.action, factory: offline }

    csbill.payment.payum.extension.update_payment_details_extension:
        class: CSBill\PaymentBundle\Payum\Extension\UpdatePaymentDetailsExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: payum.extension, all: true }

    csbill.payment.method.options:
        class: CSBill\PaymentBundle\Manager\PaymentSettingsManager
        arguments: [@doctrine]

    csbill.payment.twig_extension:
        class: CSBill\PaymentBundle\Twig\PaymentExtension
        arguments: [@doctrine]
        tags:
            - { name: twig.extension }

    csbill.payment.listener.payment_complete_listener:
        class: CSBill\PaymentBundle\Listener\PaymentCompleteListener
        arguments: [@invoice.manager, @doctrine.orm.entity_manager, @session, @translator, @router, @currency]
        tags:
            - { name: kernel.event_listener, event: payment.complete, method: onPaymentComplete }

    csbill.payment.notification.listener.payment_listener:
        class: CSBill\PaymentBundle\Listener\PaymentReceivedListener
        arguments: [@notification.manager]
        tags:
            - { name: kernel.event_listener, event: payment.complete, method: onPaymentCapture }