parameters:
    csbill_payment.menu.top.class: CSBill\PaymentBundle\Menu\Builder
services:
    csbill_payment.menu.top:
        class: '%csbill_payment.menu.top.class%'
        tags:
            - { name: cs_core.menu, menu: top_right, method: topRightMenu }
            - { name: cs_core.menu, menu: top, method: topMenu, priority: -1 }

    csbill.payment.payum.paypal_express.action.payment_status_action:
        class: CSBill\PaymentBundle\Action\PaypalExpress\PaymentDetailsStatusAction
        tags:
            - { name: payum.action, factory: paypal_express_checkout, prepend: true }

    csbill.payment.payum.offline.action.status_action:
        class: CSBill\PaymentBundle\Action\Offline\StatusAction
        tags:
            - { name: payum.action, factory: offline }

    csbill.payment.payum.extension.update_payment_details_extension:
        class: CSBill\PaymentBundle\Payum\Extension\UpdatePaymentDetailsExtension
        arguments:
            - '@doctrine'
        tags:
            - { name: payum.extension, all: true }

    csbill.payment.method.options:
        class: CSBill\PaymentBundle\Manager\PaymentSettingsManager
        arguments:
            - '@doctrine'
    csbill.payment.twig_extension:
        class: CSBill\PaymentBundle\Twig\PaymentExtension
        arguments:
            - '@doctrine'
            - '@currency'
        tags:
            - { name: twig.extension }

    csbill.payment.listener.payment_complete_listener:
        class: CSBill\PaymentBundle\Listener\PaymentCompleteListener
        arguments:
            - '@invoice.manager'
            - '@doctrine'
            - '@session'
            - '@translator'
            - '@router'
            - '@currency'
        tags:
            - { name: kernel.event_listener, event: payment.complete, method: onPaymentComplete }

    csbill.payment.notification.listener.payment_listener:
        class: CSBill\PaymentBundle\Listener\PaymentReceivedListener
        arguments:
            - '@notification.manager'
        tags:
            - { name: kernel.event_listener, event: payment.complete, method: onPaymentCapture }
