config:
    shim:
        admin-lte:
            deps:
                - bootstrap
        bootstrap:
            deps:
                - jquery
        jquery.select2:
            deps:
                - jquery
            exports: Select2
        jquery.jqcron:
            deps:
                - jquery
        jquery.placeholder:
            deps:
                - jquery
        jquery.uploadify:
            deps:
                - jquery
        bootstrap.modal:
            deps:
                - jquery
                - bootstrap
        bootstrap.modalmanager:
            deps:
                - jquery
                - bootstrap
        bootstrap.material.datetimepicker:
            deps:
                - jquery
                - moment
        material:
            deps:
                - jquery
                - material.ripples
        material.ripples:
            deps:
                - jquery
        fos_router:
            exports: fos.Router
    paths:
        # External dependencies loaded through NPM/Yarn
        backbone: ../assets/backbone.js
        backbone.paginator: ../assets/backbone.paginator.js
        backbone.radio: ../assets/backbone.radio.js
        marionette: ../assets/backbone.marionette.js
        lodash: ../assets/index.js
        jquery: ../assets/jquery.js
        bootstrap: ../assets/bootstrap.js
        accounting: ../assets/accounting.js
        parsley: ../assets/parsley.js
        moment: ../assets/moment.js
        material: ../assets/material.js
        material.ripples: ../assets/ripples.js
        jquery.select2: ../assets/select2.js
        handlebars.runtime: ../assets/handlebars.runtime.js
        bootstrap.bootbox: ../assets/bootbox.js
        jquery.placeholder: ../assets/jquery.placeholder.js
        bootstrap.material.datetimepicker: ../assets/material-datetimepicker.js
        admin-lte: ../assets/app.min.js

        # External Dependencies that don't have an NPM package
        jquery.jqcron: csbillcore/js/lib/jquery/jqcron.js
        jquery.uploadify: csbillcore/js/lib/jquery/uploadify.min.js
        bootstrap.modal: csbillcore/js/lib/bootstrap/modal.js
        bootstrap.modalmanager: csbillcore/js/lib/bootstrap/modalmanager.js

        routing: csbillcore/js/extend/routing
        fos_router: fosjsrouting/js/router.js
        fos_routing_data: ../js/fos_js_routes
        Translator: bazingajstranslation/js/translator.min.js
        core: csbillcore/js/
        core/view: csbillcore/js/itemview.js
        util/form/collection: csbillcore/js/util/form/collection.js
        template: ../js/hbs-templates.js
        fos_routing_data: ../js/fos_js_routes.js
    map:
        '*':
            translator: csbillcore/js/extend/translator
            underscore: lodash
            handlebars.runtime: csbillcore/js/extend/handlebars/helpers
            parsley: csbillcore/js/extend/parsley
            bootstrap.modal: csbillcore/js/extend/modal
        csbillcore/js/extend/handlebars/helpers:
            handlebars.runtime: handlebars.runtime
            routing: routing
        csbillcore/js/extend/translator:
            translation_data: translation_data
        csbillcore/js/extend/parsley:
            parsley: parsley
        csbillcore/js/extend/modal:
            bootstrap.modal: bootstrap.modal
build:
    paths:
        core: 'empty:'
        client: 'empty:'
        quote: 'empty:'
        invoice: 'empty:'
        profile: 'empty:'
        payments: 'empty:'
        moment: 'empty:'
        grid: 'empty:'
        translation_data: 'empty:'
        bootstrap.material.datetimepicker: 'empty:'
