_home:
    path: /
    defaults: { _controller: 'FrameworkBundle:Redirect:redirect', route: _dashboard, permanent: true }

_image_upload:
    path: /upload
    defaults: { _controller: 'CSBill\CoreBundle\Action\Upload' }
    options:
        expose: true

_view_quote_external:
    path: '/view/quote/{uuid}'
    defaults: { _controller: 'CSBill\CoreBundle\Action\ViewBilling::quoteAction' }
    requirements:
        uuid: '[a-zA-Z0-9-]{36}'

_view_invoice_external:
    path: '/view/invoice/{uuid}'
    defaults: { _controller: 'CSBill\CoreBundle\Action\ViewBilling::invoiceAction' }
    requirements:
        uuid: '[a-zA-Z0-9-]{36}'
