services:
    currency:
        class: Money\Currency
        arguments: ['%currency%']

    csbill.money.formatter:
        class: CSBill\MoneyBundle\Formatter\MoneyFormatter
        arguments: ['%locale%', '%currency%']