_invoices_index:
    path: /
    defaults: { _controller: 'CSBill\InvoiceBundle\Action\Index' }

_invoices_create:
    path: '/create/{client}'
    defaults: { _controller: 'CSBill\InvoiceBundle\Action\Create', client: null }
    options:
        expose: true

_invoices_get_fields:
    path: '/fields/get'
    defaults: { _controller: 'CSBill\InvoiceBundle\Action\Fields' }
    options:
        expose: true

_invoices_edit:
    path: '/edit/{id}'
    defaults: { _controller: 'CSBill\InvoiceBundle\Action\Edit' }
    options:
        expose: true

_invoices_view:
    path: '/view/{id}'
    defaults: { _controller: 'CSBill\InvoiceBundle\Action\View' }
    options:
        expose: true

_invoices_clone:
    path: '/clone/{id}'
    defaults: { _controller: 'CSBill\InvoiceBundle\Action\CloneInvoice' }

_send_invoice:
    path: '/action/send/{id}'
    defaults:  { _controller: 'CSBill\InvoiceBundle\Action\Transition\Send' }

_action_invoice:
    path: '/action/{action}/{id}'
    defaults: { _controller: 'CSBill\InvoiceBundle\Action\Transition' }

_invoicess_grid:
    resource: '@CSBillInvoiceBundle/Action/Grid'
    type: grid