_invoices_index:
    path: /
    defaults: { _controller: 'SolidInvoice\InvoiceBundle\Action\Index' }

_invoices_create:
    path: '/create/{client}'
    defaults: { _controller: 'SolidInvoice\InvoiceBundle\Action\Create', client: null }
    options:
        expose: true

_invoices_get_fields:
    path: '/fields/get/{currency}'
    defaults: { _controller: 'SolidInvoice\InvoiceBundle\Action\Fields' }
    options:
        expose: true

_invoices_edit:
    path: '/edit/{id}'
    defaults: { _controller: 'SolidInvoice\InvoiceBundle\Action\Edit' }
    options:
        expose: true

_invoices_view:
    path: '/view/{id}.{_format}'
    defaults: { _controller: 'SolidInvoice\InvoiceBundle\Action\View', _format: html }
    requirements:
        _format: html|pdf
    options:
        expose: true

_invoices_clone:
    path: '/clone/{id}'
    defaults: { _controller: 'SolidInvoice\InvoiceBundle\Action\CloneInvoice' }

_send_invoice:
    path: '/action/send/{id}'
    defaults:  { _controller: 'SolidInvoice\InvoiceBundle\Action\Transition\Send' }

_action_invoice:
    path: '/action/{action}/{id}'
    defaults: { _controller: 'SolidInvoice\InvoiceBundle\Action\Transition' }

_invoices_grid:
    resource: '@SolidInvoiceInvoiceBundle/Action/Grid'
    type: grid