_invoices_index:
    path: /
    defaults: { _controller: 'CSBillInvoiceBundle:Default:index' }

_invoices_create:
    path: '/create/{client}'
    defaults: { _controller: 'CSBillInvoiceBundle:Default:create', client: null }
    options:
        expose: true

_invoices_get_fields:
    path: '/fields/get'
    defaults: { _controller: 'CSBillInvoiceBundle:Default:getFields' }
    options:
        expose: true

_invoices_edit:
    path: '/edit/{id}'
    defaults: { _controller: 'CSBillInvoiceBundle:Default:edit' }
    options:
        expose: true

_invoices_view:
    path: '/view/{id}'
    defaults: { _controller: 'CSBillInvoiceBundle:Default:view' }
    options:
        expose: true

_invoices_clone:
    path: '/clone/{id}'
    defaults: { _controller: 'CSBillInvoiceBundle:Default:clone' }

_send_invoice:
    path: '/action/send/{id}'
    defaults:  { _controller: 'CSBillInvoiceBundle:Actions:send' }

_action_invoice:
    path: '/action/{action}/{id}'
    defaults: { _controller: 'CSBillInvoiceBundle:Actions:transition' }

_invoices_archive:
    path: /archive
    defaults: { _controller: 'CSBillInvoiceBundle:Grid:archive' }
    methods: [POST]
    options:
        expose: true

_invoices_delete:
    path: /delete
    defaults: { _controller: 'CSBillInvoiceBundle:Grid:delete' }
    methods: [POST]
    options:
        expose: true
