parameters:
    csbill_core.doctrine.type.money.class: CSBill\MoneyBundle\Form\Extension\MoneyExtension
    csbill_money.form.type.hidden_money.class: CSBill\MoneyBundle\Form\Type\HiddenMoneyType
services:
    currency:
        class: Money\Currency
        arguments:
            - '%currency%'
    csbill.money.formatter:
        class: CSBill\MoneyBundle\Formatter\MoneyFormatter
        arguments:
            - '%locale%'
            - '%currency%'
    csbill.money.formatter.twig.extension:
        class: CSBill\MoneyBundle\Twig\Extension\MoneyFormatterExtension
        arguments:
            - '@csbill.money.formatter'
            - '@currency'
        tags:
            - { name: twig.extension }

    csbill_money.form.money.extension:
        class: '%csbill_core.doctrine.type.money.class%'
        arguments:
            - '@currency'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\MoneyType }

    csbill_money.form.hidden_money.type:
        class: '%csbill_money.form.type.hidden_money.class%'
        arguments:
            - '@currency'
        tags:
            - { name: form.type }
