services:
    _defaults:
        tags: ['form.handler']

    _instanceof:
        SolidWorx\FormHandler\FormHandlerInterface:
            autowire: true
            public: false

    SolidInvoice\UserBundle\Form\Handler\:
        resource: '../../../Form/Handler'
        lazy: true

    SolidInvoice\UserBundle\Form\Handler\UserAddFormHandler:
        arguments:
            $factory: '@fos_user.registration.form.factory'

    SolidInvoice\UserBundle\Form\Handler\UserEditFormHandler:
        arguments:
            $factory: '@solidinvoice.user.profile.form_factory'