services:
    fos_user.user_manager.default:
        class: SolidInvoice\UserBundle\Manager\UserManager
        public: false
        lazy: true
        arguments: ['@fos_user.util.password_updater', '@fos_user.util.canonical_fields_updater', '@fos_user.object_manager', '%fos_user.model.user.class%']

    SolidInvoice\UserBundle\Repository\ApiTokenRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\ApiTokenHistoryRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\UserRepository:
        autowire: true
        tags: ['doctrine.repository_service']
