services:
    SolidInvoice\UserBundle\Repository\ApiTokenRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\ApiTokenHistoryRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\UserRepository:
        autowire: true
        tags: ['doctrine.repository_service']
