services:
    SolidInvoice\UserBundle\Manager\UserManager: '@fos_user.user_manager.default'

    SolidInvoice\UserBundle\Repository\ApiTokenRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\ApiTokenHistoryRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\UserRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    # Fixtures
    SolidInvoice\UserBundle\DataFixtures\ORM\:
        resource: '%kernel.project_dir%/src/UserBundle/DataFixtures/ORM/*'
        tags: ['doctrine.fixture.orm']
