language: php

sudo: false

dist: trusty

php:
  - 7.1

matrix:
  fast_finish: true

env:
  global:
    - SYMFONY_ENV=test

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

services:
  - mysql

addons:
  sauce_connect:
    username: csbill
  jwt:
    secure: "bFt4pHewWZzmtSH4cKg3L9CRylqAPuVnBDTYGAFsWemLHx+kXHtB8JMCVEOg4M/Q1cUedB2kYJTr+H2/ZkEREIGWg76d+ODZaqKBz1vsU/s86QVZ92XhkCbr1lchwU6/cs/UxcVfkyfs9Bhh/lzSss42X/5Y50gxeE1eGXXVxoQ="
  #apt:
  #  sources:
  #    - google-chrome
  #  packages:
  #    - google-chrome-beta

before_install:
  - composer self-update
  #- google-chrome-beta --headless --disable-gpu --remote-debugging-port=9222 &> /dev/null &

install:
  - composer install -n
  - sed -i 's/base_url:\ null/base_url:\ http:\/\/127.0.0.1:9001/g' app/config/parameters.yml
  - php bin/console cache:clear
  - npm install
  - php bin/console assets:install -n
  - node_modules/.bin/gulp

before_script:
  - mysql -e 'create database csbill;'
  - echo "xdebug.max_nesting_level=500" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php app/app_check.php
  #- bash travis/travis-ci-apache.sh
  #- node_modules/.bin/gulp
  - php ./bin/console server:start 9001 -n
  - sleep 5
  - curl http://127.0.0.1:9001/

script:
  - composer validate
  #- php bin/console security:check # Security checker SSL is currently broken
  #- ./bin/phpstan analyse ./src -vvv --level=1 -c phpstan.neon
  - bash travis/behat.sh
  - bash travis/phpunit.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - travis_retry php ./bin/coveralls -v

notifications:
  #webhooks:
    #- http://savage.csbill.org/savage/travis
  hipchat:
    rooms:
      secure: Wc5cg/o//7DW9G0mosA5wmmECr9+R7S/FmVFvZU2mBBpfaE5nY873hePRrMK/Dhiu2aD5R/ll6d7b3mT7oiWzO/rMgQ+U/DcMmgqHYiYrtEz4umi+1EuSLURDAxyv3rDiXHhEWwbYcHfE1Tcfs07Aj4JWSZheploBRpg3iqzMbw=
