language: php

sudo: required

dist: trusty

env:
  global:
    - SOLIDINVOICE_ENV=test
    - SOLIDINVOICE_DEBUG=0
    - database_name=solidinvoice_test
    - PATH="$HOME/.symfony/bin:$PATH"

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules

services:
  - mysql

addons:
  chrome: stable
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_install:
  - composer self-update
  - mysql -e 'create database solidinvoice_test;'

install:
  - composer install -n
  - sed -i 's/base_url:\ null/base_url:\ http:\/\/127.0.0.1:8000/g' app/config/parameters.yml

before_script:
  - echo "xdebug.max_nesting_level=500" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php app/app_check.php

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot
  include:
    - stage: unit
      php: 7.1
      script:
        - composer validate
        #- php bin/console security:check
        - bash travis/phpunit.sh
        - ./bin/phpstan analyse ./src -vvv --level=1 -c phpstan.neon
      after_script:
        - travis_retry wget https://scrutinizer-ci.com/ocular.phar
        - travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
        - travis_retry php ./bin/php-coveralls -v
    - stage: unit
      php: 7.2
      script: bash travis/phpunit.sh
    - stage: unit
      php: 7.3
      script: bash travis/phpunit.sh
    - stage: unit
      php: nightly
      script: bash travis/phpunit.sh
    - stage: unit
      php: 7.4snapshot
      script: bash travis/phpunit.sh
    - stage: functional
      php: 7.2
      before_install:
        - mysql -e "create database ${database_name};"
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn=0.24.6-1
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout $(git describe --abbrev=0 --tags)) && source ~/.nvm/nvm.sh && nvm install 12.0
        - curl -sS https://get.symfony.com/cli/installer | bash
      install:
        - composer install -n
        - curl -o vendor/symfony/panther/chromedriver-bin/chromedriver_linux64 https://raw.githubusercontent.com/symfony/panther/master/chromedriver-bin/chromedriver_linux64
        - sed -i 's/base_url:\ null/base_url:\ https:\/\/127.0.0.1:8000/g' app/config/parameters.yml
        - sed -i 's/database_name:\ solidinvoice/database_name:\ solidinvoice_test/g' app/config/parameters.yml
        - rm -Rf var/cache/test
        - yarn
        - yarn run dev
      before_script:
          - symfony server:ca:install
          - symfony local:server:start --daemon
      script: bash travis/functional.sh

notifications:
    slack:
        secure: jAXgCz5/ZxAnFN/x73gH8may6Vd5OJsfg4bX/1/QcAybP5J77P7vBBnJNVU3vsjTBrl24cAyfqwE/bUz9ZqLGKb1P3RglLmZAIhE92V76QDE+zpbPxt2rGCBIdGFrkRCFsR4AthfjroTWg4cWA9GGxISkNj4+K3hcbKQZzs0nz7VzrXLX2IywwlcHV75XHy8SpAeGCG1ZqYqc6vVhO3E777kz9n+b5HoTYp8GiRbh7X0FKQ9CdzRdpvc217+0XoL+v6MWBWjAV2YOm7XcXsfe79U3Iip7Cs42q23G7KGNoF3292W+CiZ2w25B6YFvxiep+tcioCx2xMaWPZ7lYAApjh7O/mgJKBtd3hQUWNm0KKKyKnJ3g9b5ZX0qagkv3DFYo7vU/Y+41HIm1D2EckgBYTKkcnprCb9nmf19l6h+SKwiVZfJdQS8ScNfUtADBd7s8csjaM3jG7KCK4yKU4JQLvEQmlzyPE3ngXMjlb3U9NoloMZuN2ukhDF2oRedL4mP8j4S9JbyhTBytXXyzr5wMBzdpXgI3TZngbZM0d1wbbuGm9VEWLQG5PJQtW3WkX9bs7dzu5iRttjDyRfyKXF7ZVYmW59Ox3J54c8zNSQVy/uVdwrX4nvh8jPQ4oh3BJvsQwX+HbW9+tdRhyKBsH9l8JALRCfY4AP4TxziohMsMw=
