language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

sudo: false

before_install:
  - composer self-update

install:
    - composer install --prefer-source --no-interaction

before_script:
    - mysql -e 'create database csbill;'

script:
    - ./bin/phpunit -c app

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
