language: php

sudo: required

dist: trusty

#php:
#  - 7.1
#  - nightly

#matrix:
#  fast_finish: true
#  allow_failures:
#]    - php: nightly

env:
  global:
    - SYMFONY_ENV=test

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

services:
  - mysql

addons:
  sauce_connect:
    username: csbill
  jwt:
    secure: "bFt4pHewWZzmtSH4cKg3L9CRylqAPuVnBDTYGAFsWemLHx+kXHtB8JMCVEOg4M/Q1cUedB2kYJTr+H2/ZkEREIGWg76d+ODZaqKBz1vsU/s86QVZ92XhkCbr1lchwU6/cs/UxcVfkyfs9Bhh/lzSss42X/5Y50gxeE1eGXXVxoQ="
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_install:
  - composer self-update

install:
  - composer install -n
  - sed -i 's/base_url:\ null/base_url:\ http:\/\/127.0.0.1:9001/g' app/config/parameters.yml
  - php bin/console cache:clear
  - npm install
  - php bin/console assets:install -n
  - php bin/console fos:js-routing:dump
  - node_modules/.bin/gulp

before_script:
  - mysql -e 'create database csbill;'
  - echo "xdebug.max_nesting_level=500" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php app/app_check.php
  - php ./bin/console server:start 9001 -n
  - sleep 5 # Give php server some time to start

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - stage: unit
      php: 7.1
      script:
        - composer validate
        #- php bin/console security:check # Security checker SSL is currently broken
        - ./bin/phpstan analyse ./src -vvv --level=1 -c phpstan.neon
        - bash travis/phpunit.sh
    - stage: unit
      php: nightly
      script:
        - composer validate
        #- php bin/console security:check # Security checker SSL is currently broken
        - ./bin/phpstan analyse ./src -vvv --level=1 -c phpstan.neon
        - bash travis/phpunit.sh
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_linux
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_linux
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_opera_linux
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_stable_macos_sierra
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_dev_macos_sierra
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_beta_macos_sierra
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_stable_macos_sierra
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_dev_macos_sierra
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_beta_macos_sierra
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_safari_macos_sierra
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_stable_osx_el_capitan
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_dev_osx_el_capitan
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_beta_osx_el_capitan
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_stable_osx_el_capitan
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_dev_osx_el_capitan
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_beta_osx_el_capitan
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_safari_10_osx_el_capitan
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_safari_9_osx_el_capitan
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_stable_windows10
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_dev_windows10
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_beta_windows10
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_stable_windows10
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_dev_windows10
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_beta_windows10
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_ie_windows10
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_edge_14_windows10
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_edge_13_windows10
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_stable_windows81
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_dev_windows81
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_chrome_beta_windows81
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_stable_windows81
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_stable_windows81
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_dev_windows81
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_firefox_beta_windows81
    - stage: functional
      php: 7.1
      script: bash travis/behat.sh
      env: TEST_SUITE=saucelabs_ie_windows81

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - travis_retry php ./bin/coveralls -v

notifications:
  hipchat:
    rooms:
      secure: Wc5cg/o//7DW9G0mosA5wmmECr9+R7S/FmVFvZU2mBBpfaE5nY873hePRrMK/Dhiu2aD5R/ll6d7b3mT7oiWzO/rMgQ+U/DcMmgqHYiYrtEz4umi+1EuSLURDAxyv3rDiXHhEWwbYcHfE1Tcfs07Aj4JWSZheploBRpg3iqzMbw=
