datagrid:
    active_client_grid:
	title: Active
	icon: check
	source:
	    repository: 'CSBillClientBundle:Client'
	    method: getGridQuery
	columns:
	    id:
		name: id
		label: ID
		editable: false
		cell: integer
	    name:
		name: name
		label: Name
		editable: false
		cell: string
	    website:
		name: website
		label: Website
		editable: false
		cell: uri
	    status:
		name: status
		label: Status
		editable: false
		cell: client_status
	    created:
		name: created
		label: Created
		editable: false
		cell: date
	search:
	    fields:
		- name
		- website
		- status
	line_actions:
	    view:
		icon: eye
		label: client.grid.actions.view
		route: _clients_view
		route_params:
		    id: id
	    edit:
		icon: edit
		label: client.grid.actions.edit
		route: _clients_edit
		route_params:
		    id: id
	actions:
	    archive:
		label: Archive
		icon: archive
		confirm: 'Are you sure you want to archive the selected rows?'
		action: _clients_archive
		className: warning
	    delete:
		label: Delete
		icon: ban
		confirm: 'Are you sure you want to delete the selected rows?'
		action: _clients_delete
		className: danger
    archive_client_grid:
	title: Archived
	icon: archive
	source:
	    repository: 'CSBillClientBundle:Client'
	    method: getArchivedGridQuery
	columns:
	    id:
		name: id
		label: ID
		editable: false
		cell: integer
	    name:
		name: name
		label: Name
		editable: false
		cell: string
	    website:
		name: website
		label: Website
		editable: false
		cell: uri
	    status:
		name: status
		label: Status
		editable: false
		cell: client_status
	    created:
		name: created
		label: Created
		editable: false
		cell: date
	search:
	    fields:
		- name
		- website
		- status
	actions:
	    restore:
		label: Restore
		icon: archive
		confirm: 'Are you sure you want to restore the selected rows?'
		action: _clients_restore
		className: info
	    delete:
		label: Delete
		icon: ban
		confirm: 'Are you sure you want to delete the selected rows?'
		action: _clients_delete
		className: danger
