parameters:
    csbill_client.menu.class: CSBill\ClientBundle\Menu\Builder
    csbill_client.contact_type.repository.class: CSBill\ClientBundle\Repository\ContactTypeRepository

services:
    csbill_client.menu:
	class: '%csbill_client.menu.class%'
	tags:
	    - { name: cs_core.menu, menu: top, method: topMenu }
	    - { name: cs_core.menu, menu: clients_index, method: clientsMenu }
	    - { name: cs_core.menu, menu: clients_view, method: clientViewMenu }
	    - { name: cs_core.menu, menu: clients_add, method: clientsMenu }
	    - { name: cs_core.menu, menu: clients_edit, method: clientsMenu }

    csbill_client.contact.form.type:
	class: CSBill\ClientBundle\Form\Type\ContactType
	tags:
	    - { name: form.type }

    csbill_client.contact_detail.form.type:
	class: CSBill\ClientBundle\Form\Type\ContactDetailType
	arguments:
	    - '@csbill_client.contact_type.values'
	tags:
	    - { name: form.type }

    csbill_client.contact_type.repository:
	class: '%csbill_client.contact_type.repository.class%'
	factory: ['@doctrine', getRepository]
	arguments:
	    - 'CSBillClientBundle:ContactType'

    csbill_client.contact_type.values:
	class: '%csbill_client.contact_type.repository.class%'
	factory: ['@csbill_client.contact_type.repository', findAll]

    client.notification.listener:
	class: CSBill\ClientBundle\Listener\ClientListener
	calls:
	    - ['setContainer', ['@service_container']]
	tags:
	    - { name: doctrine.event_listener, event: postPersist }
	    - { name: doctrine.event_listener, event: postUpdate }

    csbill.serializer.credit.handler:
	class: CSBill\ClientBundle\Serializer\Handler\CreditHandler
	arguments:
	    - '@csbill.money.formatter'
	tags:
	    - { name: jms_serializer.handler, type: 'Money\Money', direction: serialization, format: json, method: serializeMoneyJson }
	    - { name: jms_serializer.handler, type: 'Money\Money', direction: serialization, format: xml, method: serializeMoneyXml }
	    - { name: jms_serializer.handler, type: 'CSBill\MoneyBundle\Entity\Money', direction: serialization, format: xml, method: serializeMoneyXml }
