config:
    shim:
        backgrid:
            deps:
                - backbone
                - lodash
            exports: Backgrid
        grid/backgrid-filter:
            deps:
                - backgrid
        grid/backgrid-paginator:
            deps:
                - backgrid
        grid/backgrid-select-all:
            deps:
                - backgrid
    paths:
        backgrid: csbilldatagrid/js/backgrid.js
        grid: csbilldatagrid/js/
