services:
    _defaults:
        public: false
        tags:
            - { name: kernel.event_subscriber }

    CSBill\CoreBundle\Listener\DoctrineExtensionListener:
        calls:
            - [setContainer, ['@service_container']]

    CSBill\CoreBundle\Listener\SessionRequestListener:
        arguments: ['@session', '@security.encryption']