services:
    _instanceof:
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            autowire: true
            public: false
            tags:
                - { name: kernel.event_subscriber }

    CSBill\CoreBundle\Listener\:
        resource: '../../../Listener'

    CSBill\CoreBundle\Listener\DoctrineExtensionListener:
        calls:
            - [setContainer, ['@service_container']]

    CSBill\CoreBundle\Listener\SessionRequestListener:
        arguments:
            $secret: '%secret%'

    CSBill\CoreBundle\Listener\TemplateListener: ~
