services:
    _defaults:
        autowire: true
        autoconfigure: true

    SolidInvoice\CoreBundle\ConfigWriter:
        arguments:
            $cacheDir: '%kernel.cache_dir%'
            $projectDir: '%kernel.project_dir%'

    solidinvoice_core.form.help.extension:
        class: SolidInvoice\CoreBundle\Form\Extension\FormHelpExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    solidinvoice_core.cssinline:
        class: TijsVerkoyen\CssToInlineStyles\CssToInlineStyles
        public: false

    solidinvoice_menu.top:
        class: SolidInvoice\CoreBundle\Menu\Builder
        tags:
            - { name: cs_core.menu, menu: top_right, method: systemMenu, priority: 255 }
            - { name: cs_core.menu, menu: top_right, method: userMenu, priority: 255 }

    SolidInvoice\CoreBundle\Form\FieldRenderer:
        lazy: true

    SolidInvoice\CoreBundle\Routing\Loader\AbstractDirectoryLoader:
        public: false
        lazy: true
        abstract: true
        arguments:
            $locator: '@file_locator'
            $kernel: '@kernel'

    Mpociot\VatCalculator\VatCalculator: ~
    SolidInvoice\CoreBundle\Billing\TotalCalculator: ~

    SolidInvoice\CoreBundle\Email\Decorator\:
        resource: '../../../Email/Decorator/'
        tags: ['message.decorator']

    SolidInvoice\CoreBundle\Pdf\Generator:
        bind:
            $cacheDir: '%kernel.cache_dir%'

    SolidInvoice\CoreBundle\Repository\VersionRepository:
        tags: ['doctrine.repository_service']

    SolidInvoice\CoreBundle\Command\YamlFormatCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
