services:
    api_token_authenticator:
        class:     CSBill\ApiBundle\Security\ApiTokenAuthenticator
        arguments: [@api_token_user_provider, @serializer, @doctrine]

    api_token_user_provider:
        class: CSBill\ApiBundle\Security\Provider\ApiTokenUserProvider
        arguments: [@doctrine]
