services:
    _instanceof:
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            public: false
            tags: ['kernel.event_subscriber']

    _defaults:
        public: false
        autowire: true

    CSBill\InvoiceBundle\Listener\:
        resource: '../../../Listener'