services:
    _defaults:
        public: false
        autowire: true
        tags:
            - { name: form.type }

    CSBill\InvoiceBundle\Form\Type\InvoiceType: ~

    CSBill\InvoiceBundle\Form\Type\ItemType: ~