services:
    solidinvoice_invoice.menu:
        class: SolidInvoice\InvoiceBundle\Menu\Builder
        tags:
            - { name: cs_core.menu, menu: top, method: topMenu }
            - { name: cs_core.menu, menu: invoices_index,  method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_view,   method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_create, method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_edit, method: invoicesEditMenu }

    SolidInvoice\InvoiceBundle\Manager\InvoiceManager:
        autowire: true
        arguments:
            $stateMachine: '@state_machine.invoice'
        calls:
            - [ setContainer, ['@service_container']]

    SolidInvoice\InvoiceBundle\Listener\Doctrine\InvoiceSaveListener:
        arguments: ['@solidinvoice.payment.locator']
        tags: ['doctrine.event_subscriber']

    SolidInvoice\InvoiceBundle\Cron\RecurringInvoiceCreate:
        autowire: true
        arguments:
            $stateMachine: '@state_machine.invoice'
        tags:
            - { name: cron.command }

    SolidInvoice\InvoiceBundle\Cloner\InvoiceCloner:
        autowire: true

    SolidInvoice\InvoiceBundle\Email\Decorator\:
        autowire: true
        resource: '../../../Email/Decorator/'
        tags: ['message.decorator']

    SolidInvoice\InvoiceBundle\Repository\InvoiceRepository:
        autowire: true
        tags: ['doctrine.repository_service']
