services:
    csbill_invoice.menu:
        class: CSBill\InvoiceBundle\Menu\Builder
        tags:
            - { name: cs_core.menu, menu: top, method: topMenu }
            - { name: cs_core.menu, menu: invoices_index,  method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_view,   method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_create, method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_edit, method: invoicesEditMenu }

    CSBill\InvoiceBundle\Repository\InvoiceRepository:
        factory: ['@doctrine', getRepository]
        arguments: ['CSBillInvoiceBundle:Invoice']

    invoice.manager:
        class: CSBill\InvoiceBundle\Manager\InvoiceManager
        autowire: true
        calls:
            - [ setContainer, ['@service_container']]

    invoice.user.listener:
        class: CSBill\InvoiceBundle\Listener\Doctrine\InvoiceUsersListener
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    csbill.cron.recurring_invoice.create:
        class: CSBill\InvoiceBundle\Cron\RecurringInvoiceCreate
        autowire: true
        tags:
            - { name: cron.command }
