services:
    _defaults:
        public: false
        tags:
            - { name: kernel.event_subscriber }

    CSBill\QuoteBundle\Listener\Mailer\QuoteMailerListener:
        arguments: ['@billing.mailer']