services:
    _instanceof:
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            public: false
            tags: ['kernel.event_subscriber']

    _defaults:
        public: false
        autowire: true

    CSBill\QuoteBundle\Listener\:
        resource: '../../../Listener'

    CSBill\QuoteBundle\Listener\WorkFlowSubscriber:
        arguments:
            $invoiceStateMachine: '@state_machine.invoice'