services:
    quote.manager:
        class: CSBill\QuoteBundle\Manager\QuoteManager
        autowire: true
        arguments:
            $stateMachine: '@state_machine.quote'

    CSBill\QuoteBundle\Menu\Builder:
        public: false
        tags:
            - { name: cs_core.menu, menu: top, method: topMenu }
            - { name: cs_core.menu, menu: quotes_index,  method: quotesMenu }
            - { name: cs_core.menu, menu: quotes_view,   method: quotesMenu }
            - { name: cs_core.menu, menu: quotes_create, method: quotesMenu }
            - { name: cs_core.menu, menu: quotes_edit, method: quotesEditMenu }

    CSBill\QuoteBundle\Listener\Doctrine\QuoteUsersListener:
        public: false
        lazy: true
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    CSBill\QuoteBundle\Cloner\QuoteCloner:
        autowire: true
        arguments:
            $stateMachine: '@state_machine.quote'