services:
    _instanceof:
        SolidWorx\FormHandler\FormHandlerInterface:
            autowire: true
            public: false
            tags:
                - { name: 'form.handler' }

    CSBill\ClientBundle\Form\Handler\:
        resource: '../../../Form/Handler'
        lazy: true
