imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: payum.yml }
    - { resource: workflow.yml }
    - { resource: assetVersion.php }
    - { resource: '@CSBillInvoiceBundle/Resources/config/finite.yml' }
    - { resource: '@CSBillQuoteBundle/Resources/config/finite.yml' }

framework:
    esi: null
    translator:
        fallback: en
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: null
    form: null
    csrf_protection: null
    validation:
        enabled: true
        enable_annotations: true
        strict_email: true
    default_locale: '%locale%'
    session:
        name: CSBILL_APP
    fragments: null
    http_method_override: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'CSBillCoreBundle:Form:fields.html.twig'

doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            money: CSBill\MoneyBundle\Doctrine\Types\MoneyType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                hydrators:
                    money: CSBill\MoneyBundle\Doctrine\Hydrator\MoneyHydrator
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                    archivable:
                        class: CSBill\CoreBundle\Doctrine\Filter\ArchivableFilter
                        enabled: true
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity'
                        alias: GedmoTranslatable
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity'
                        alias: GedmoTranslator
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity'
                        alias: GedmoLoggable
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity'
                        alias: GedmoTree
                        is_bundle: false
                    payum:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping'
                        prefix: Payum\Core\Model

swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool:
        type: memory

stof_doctrine_extensions:
    default_locale: '%locale%'
    orm: null

fos_user:
    from_email:
        address: 'info@csbill.org'
        sender_name: 'CSBill'
    db_driver: orm
    firewall_name: main
    user_class: CSBill\UserBundle\Entity\User
    profile:
        form:
            type: CSBill\UserBundle\Form\Type\ProfileType
fos_rest:
    param_fetcher_listener: true
    allowed_methods_listener: true
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true
    view:
        formats:
            jsonp: true
            json: true
            xml: true
            rss: false
            html: false
        templating_formats:
            html: false
        force_redirects:
            html: false
        serialize_null: true
        failed_validation: HTTP_BAD_REQUEST
    disable_csrf_role: ROLE_API_AUTHENTICATED
    body_listener: true
    format_listener: true
    access_denied_listener:
        json: true
        xml: true
        jsonp: true

nelmio_api_doc:
    sandbox:
        enabled: false
    cache:
        enabled: true

oro_require_js:
    config:
        waitSeconds: 0
        enforceDefine: false
        scriptType: text/javascript
    js_engine: node
