parameters:
    csbill_core.twig.globals.class: CSBill\CoreBundle\Twig\Extension\GlobalExtension
    csbill_core.twig.file.class: CSBill\CoreBundle\Twig\Extension\FileExtension
    csbill_core.twig.status.class: CSBill\CoreBundle\Twig\Extension\StatusExtension
services:
    csbill_core.twig.gobals:
        class: '%csbill_core.twig.globals.class%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: twig.extension }

    csbill_core.twig.file:
        class: '%csbill_core.twig.file.class%'
        tags:
            - { name: twig.extension }

    csbill_core.twig.status:
        class: '%csbill_core.twig.status.class%'
        tags:
            - { name: twig.extension }
