services:
    grid.repository:
        class: 'CSBill\DataGridBundle\Repository\GridRepository'

    CSBill\DataGridBundle\Routing\Loader\GridRouteLoader:
        tags: ['routing.loader']
        public: false
        lazy: true
        autowire: true
        arguments:
            $locator: '@file_locator'
            $kernel: '@kernel'
