api_login_check:
    path: /login

api_doc:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix: /docs

#client_api:
#    type: rest
#    resource: CSBill\ApiBundle\Controller\ClientController
#    prefix: /

#invoice_api:
#    type: rest
#    resource: CSBill\ApiBundle\Controller\InvoiceController
#    prefix: /

#quote_api:
#    type: rest
#    resource: CSBill\ApiBundle\Controller\QuoteController
#    prefix: /

#payment_api:
#    type: rest
#    resource: CSBill\ApiBundle\Controller\PaymentController
#    prefix: /

api:
    resource: '.'
    type:     'api_platform'