services:

    _instanceof:
        Doctrine\ORM\EntityRepository:
            factory: ['@doctrine.orm.entity_manager', 'getRepository']
            tags: ['doctrine.repository']
            lazy: true
            public: false

    CSBill\PaymentBundle\Repository\PaymentRepository:
        arguments: ['CSBill\PaymentBundle\Entity\Payment']