services:
    _defaults:
        public: false
        tags:
            - { name: kernel.event_subscriber }

    CSBill\PaymentBundle\Listener\PaymentCompleteListener:
        autowire: true

    CSBill\PaymentBundle\Listener\PaymentReceivedListener:
        arguments: ['@notification.manager']