services:
    _defaults:
        autowire: true

    SolidInvoice\MailerBundle\Mailer: ~
    SolidInvoice\MailerBundle\MessageProcessor:
        arguments:
            $decorators: !tagged message.decorator

    SolidInvoice\MailerBundle\Decorator\:
        resource: '../../Decorator/'
        tags: ['message.decorator']

