services:
    _defaults:
        autowire: true
        autoconfigure: true

    SolidInvoice\MailerBundle\Mailer: ~
    SolidInvoice\MailerBundle\MailerInterface: '@SolidInvoice\MailerBundle\Mailer'

    SolidInvoice\MailerBundle\MessageProcessor:
        arguments:
            $decorators: !tagged message.decorator

    SolidInvoice\MailerBundle\MessageProcessorInterface: '@SolidInvoice\MailerBundle\MessageProcessor'

    SolidInvoice\MailerBundle\Decorator\:
        resource: '../../Decorator/'
        tags: ['message.decorator']

    SolidInvoice\MailerBundle\Configurator\:
        resource: '../../Configurator/'
