_api_keys_index:
    path: /api
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\ApiIndex' }
    options:
        expose: true

_api_keys_xhr:
    resource: '@SolidInvoiceUserBundle/Resources/config/routing/ajax.yml'
    prefix: /api/xhr
    options:
        expose: true

_users_list:
    path: /users
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\Users' }

_user_add:
    path: /users/add
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\AddUser' }

_user_edit:
    path: /users/edit/{id}
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\EditUser' }
    options:
        expose: true
    requirements:
        id: \d+

_users_grid:
    resource: '@SolidInvoiceUserBundle/Action/Grid'
    type: grid