_quotes_index:
    path: /
    defaults: { _controller: 'CSBill\QuoteBundle\Action\Index' }

_quotes_create:
    path: '/create/{client}'
    defaults: { _controller: 'CSBill\QuoteBundle\Action\Create', client: null }
    options:
        expose: true

_quotes_get_fields:
    path: '/fields/get/{currency}'
    defaults: { _controller: 'CSBill\QuoteBundle\Action\Fields' }
    options:
        expose: true

_quotes_edit:
    path: '/edit/{id}'
    defaults: { _controller: 'CSBill\QuoteBundle\Action\Edit' }
    options:
        expose: true

_quotes_view:
    path: '/view/{id}'
    defaults: { _controller: 'CSBill\QuoteBundle\Action\View' }
    options:
        expose: true

_quotes_clone:
    path: '/clone/{id}'
    defaults: { _controller: 'CSBill\QuoteBundle\Action\CloneQuote' }

_transition_quote:
    path: '/action/{action}/{id}'
    defaults: { _controller: 'CSBill\QuoteBundle\Action\Transition' }

_quotes_grid:
    resource: '@CSBillQuoteBundle/Action/Grid'
    type: grid