services:

    _defaults:
        autowire: true

    CSBill\SettingsBundle\SystemConfig:
        lazy: true

    CSBill\SettingsBundle\Repository\SettingsRepository:
        factory: ['@doctrine', 'getRepository']
        arguments: ['CSBillSettingsBundle:Setting']

    csbill_settings.manager:
        class: CSBill\SettingsBundle\Manager\SettingsManager
        arguments: ['@doctrine']

    settings:
        alias: CSBill\SettingsBundle\SystemConfig
