services:

    _defaults:
        autowire: true
        autoconfigure: true

    SolidInvoice\SettingsBundle\SystemConfig:
        lazy: true

    settings:
        alias: SolidInvoice\SettingsBundle\SystemConfig

    SolidInvoice\SettingsBundle\Repository\SettingsRepository: ~
