services:
    csbill_settings.manager:
	class: CSBill\SettingsBundle\Manager\SettingsManager
	arguments: ['@doctrine']

    settings:
	alias: csbill_settings.manager

    csbill_settings.doctrine.loader:
	class: CSBill\SettingsBundle\Loader\DoctrineLoader
	arguments: ['@doctrine']
	tags:
	    - { name: settings.loader }
