_tax_rates:
    path: /rates
    defaults: { _controller: 'CSBill\TaxBundle\Action\Index' }

_tax_rates_add:
    path: /rates/add
    defaults: { _controller: 'CSBill\TaxBundle\Action\Add' }

_tax_rates_edit:
    path: '/rates/edit/{id}'
    defaults: { _controller: 'CSBill\TaxBundle\Action\Edit' }
    options:
        expose: true

_tax_rates_grid:
    resource: '@CSBillTaxBundle/Action/Grid'
    type: grid
