services:
    csbill.tax.twig.extension:
        class: CSBill\TaxBundle\Twig\Extension\TaxExtension
        arguments:
            - '@doctrine'
        tags:
            - { name: twig.extension, alias: tax_extension }