finite_finite:
    csbill_invoice:
        class: CSBill\InvoiceBundle\Entity\Invoice
        graph: csbill_invoice
        property_path: status
        states:
            new:
                type: initial
            draft:
                properties:
                    editable: true
                    sendable: true
            pending:
                properties:
                    editable: true
                    sendable: true
            overdue:
                properties:
                    editable: true
                    sendable: true
            cancelled: null
            archived:
                type: final
            recurring:
                type: final
            paid:
                type: final
        transitions:
            new:
                from:
                    - new
                to: draft
            recurring:
                from:
                    - new
                to: recurring
            accept:
                from:
                    - new
                    - draft
                    - overdue
                to: pending
            cancel:
                from:
                    - draft
                    - pending
                    - overdue
                to: cancelled
            overdue:
                from:
                    - pending
                to: overdue
            pay:
                from:
                    - pending
                    - overdue
                to: paid
            reopen:
                from:
                    - cancelled
                to: draft
            archive:
                from:
                    - new
                    - draft
                    - cancelled
                    - paid
                    - recurring
                to: archived
