parameters:
    csbill_invoice.menu.class: CSBill\InvoiceBundle\Menu\Main
    csbill_invoice.manager.class: CSBill\InvoiceBundle\Manager\InvoiceManager
    invoice.mailer.send_invoice.payments.class: CSBill\InvoiceBundle\Listener\Mailer\InvoiceMailerListener

services:
    csbill_invoice.menu:
        class: %csbill_invoice.menu.class%
        tags:
            - { name: cs_core.menu, menu: top, method: topMenu }
            - { name: cs_core.menu, menu: invoices_index,  method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_view,   method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_create, method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_edit, method: invoicesEditMenu }

    invoice.manager:
        class: %csbill_invoice.manager.class%
        arguments: [@doctrine, @event_dispatcher, @finite.factory, @notification.manager]
        calls:
            - [ setContainer, [@service_container]]

    invoice.mailer.send_invoice.payments:
        class: %invoice.mailer.send_invoice.payments.class%
        arguments: [@templating, @billing.mailer]
        tags:
            - { name: kernel.event_subscriber }

    invoice.user.listener:
        class: CSBill\InvoiceBundle\Listener\Doctrine\InvoiceUsersListener
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    invoice.listener.paid:
        class: CSBill\InvoiceBundle\Listener\InvoicePaidListener
        arguments: [@doctrine.orm.entity_manager, @currency]
        tags:
            - { name: kernel.event_listener, event: invoice.post_paid, method: onInvoicePaid }

    invoice.listener.cancel:
        class: CSBill\InvoiceBundle\Listener\InvoiceCancelListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: invoice.post_cancel, method: onInvoiceCancelled }

    invoice.form.type:
        class: CSBill\InvoiceBundle\Form\Type\InvoiceType
        tags:
            - { name: form.type, alias: invoice }

    invoice.item.form.type:
        class: CSBill\InvoiceBundle\Form\Type\ItemType
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: invoice_item }

    csbill.invoice.grid.default_grid:
        class: CSBill\InvoiceBundle\Grid\InvoiceGrid
        arguments: [@doctrine.orm.entity_manager, @invoice.manager, @session]


    csbill.invoice.grid.archived_grid:
        class: CSBill\InvoiceBundle\Grid\InvoiceArchivedGrid
        arguments: [@doctrine.orm.entity_manager, @session]
