services:
    _defaults:
        public: false
        tags:
            - { name: notification.handler }

    SolidInvoice\NotificationBundle\Notification\Handler\ChainedHandler:
        arguments: ['@notification.sender']

    SolidInvoice\NotificationBundle\Notification\Handler\TwilioHandler:
        autowire: true
        arguments:
            $twilio: '@twilio.client'

    Namshi\Notificator\Notification\Handler\SwiftMailer:
        arguments: ['@mailer']
