services:
    notification.sender:
        class: Namshi\Notificator\Manager
        arguments: [{}, '@logger']

    notification.manager:
        class: CSBill\NotificationBundle\Notification\NotificationManager
        arguments: ['@notification.factory', '@settings', '@notification.sender', '@doctrine']

    notification.factory:
        class: CSBill\NotificationBundle\Notification\Factory
        arguments: ['@templating', '@translator', '@settings']

    hipchat.client:
        class: HipChat\HipChat
        arguments: ['@=service(''settings'').get(''hipchat/auth_token'')', '@=service(''settings'').get(''hipchat/server_url'')']

    twilio.client:
        class: Twilio\Rest\Client
        # @TODO: Create factory to create twilio client
        #arguments: ['@=service(''settings'').get(''sms/twilio/sid'')', '@=service(''settings'').get(''sms/twilio/token'')']
        arguments: ['a', 'b']
