services:
    notification.sender:
        class: Namshi\Notificator\Manager
        arguments: [{}, '@logger']

    notification.manager:
        class: SolidInvoice\NotificationBundle\Notification\NotificationManager
        arguments: ['@notification.factory', '@settings', '@notification.sender', '@doctrine']

    notification.factory:
        class: SolidInvoice\NotificationBundle\Notification\Factory
        arguments: ['@templating', '@translator', '@settings']

    twilio.client:
        class: Twilio\Rest\Client
        # @TODO: Create factory to create twilio client
        arguments: ['@=service(''settings'').get(''sms/twilio/sid'')', '@=service(''settings'').get(''sms/twilio/token'')']
        #arguments: ['a', 'b']
