name: CS

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga

  composer-normalize:
    name: Composer Normalize

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run composer normalize
        uses: docker://ergebnis/composer-normalize-action:latest


  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v2.1.0
        env:
          VALIDATE_JAVASCRIPT_STANDARD: false
